### ISSUE TITLE
Make project iOS ready.

### ISSUE THREAD

**Issue by Harishwarrior** [CSEKINGS/student_app#12]
Currently the project is only tested in Android. We have to test and fix this project for iOS.

**Comment by yatendra2001** [comment]
Hi @Harishwarrior , I can work on this issue, Could you please assign it to me?

**Comment by Harishwarrior** [comment]
> Hi @Harishwarrior , I can work on this issue, Could you please assign it to me?

Done !. Happy hacking.

**Comment by yatendra2001** [comment]
The app is not running because firebase GoogleService-Info.plist file is missing which can be accessed by the developer id only. Else Pods are installed correctly and everything is working fine for iOS. Should I make a PR or you going to provide the file?

**Comment by yatendra2001** [comment]
The app is not running because GoogleService-Info.plist file is missing from the runner and it can be accessed through firebase ios registration only apart from it I have changed the Podfile and all pods are installed fine. So what to do next?

**Comment by Harishwarrior** [comment]
> The app is not running because GoogleService-Info.plist file is missing from the runner and it can be accessed through firebase ios registration only apart from it I have changed the Podfile and all pods are installed fine. So what to do now?

Lemme send you the files asap.

**Comment by Harishwarrior** [comment]
> The app is not running because GoogleService-Info.plist file is missing from the runner and it can be accessed through firebase ios registration only apart from it I have changed the Podfile and all pods are installed fine. So what to do now?

https://drive.google.com/file/d/1C_aQhRB6C042tuGZ_AyuCUBKgY1n62Pu/view?usp=drivesdk

**Comment by yatendra2001** [comment]
App is ready for ios, I have mentioned changes in PR.

**Comment by Harishwarrior** [comment]
> App is ready for ios, I have mentioned changes in PR.

Can you post screenshots?

**Comment by yatendra2001** [comment]
You can access screenshots through this link 
https://drive.google.com/drive/folders/1-qJhzzgEWyFQNoqTAArLohWpnmINIr-g?usp=sharing

**Comment by Harishwarrior** [comment]
#15
