### ISSUE TITLE
Fix CORS error in Firebase storage.

### ISSUE THREAD

**Issue by Harishwarrior** [CSEKINGS/student_app#14]
When we compile the application to Flutter Web. The firebase storage throws CORS error, due to that profile image is not showing up.

**Comment by devkishor8007** [comment]
Hello @Harishwarrior 

Check out this blog and I hope that your cors error will be gone
[Fixing CORS error in Firebase storage blog](https://bitmovin.com/docs/encoding/faqs/how-do-i-set-up-cors-for-my-google-cloud-storage-bucket)

**Comment by Harishwarrior** [comment]
> Hello @Harishwarrior
> 
> Check out this blog and I hope that your cors error will be gone [Fixing CORS error in Firebase storage blog](https://bitmovin.com/docs/encoding/faqs/how-do-i-set-up-cors-for-my-google-cloud-storage-bucket)

Thank you so much. It worked.

**Comment by devkishor8007** [comment]
> 
> 
> > Hello @Harishwarrior
> > Check out this blog and I hope that your cors error will be gone [Fixing CORS error in Firebase storage blog](https://bitmovin.com/docs/encoding/faqs/how-do-i-set-up-cors-for-my-google-cloud-storage-bucket)
> 
> Thank you so much. It worked.

It’s my pleasure
