### ISSUE TITLE
Notes uploading lacks progress

### ISSUE THREAD

**Issue by Harishwarrior** [CSEKINGS/student_app#7]
Would be great if we can see the progress of notes upload.

**Comment by msramesh2k1** [comment]
Hey @Harishwarrior Is this Issues comes under Hacktoberfest , so that can I work on this issue

**Comment by Harishwarrior** [comment]
> Hey @Harishwarrior Is this Issues comes under Hacktoberfest , so that can I work on this issue ,. can you please assign me on this issue

Yes it does

**Comment by msramesh2k1** [comment]
> > Hey @Harishwarrior Is this Issues comes under Hacktoberfest , so that can I work on this issue ,. can you please assign me on this issue
> 
> Yes it does

Can you please add hacktoberfest label , Thanks Man

**Comment by Harishwarrior** [comment]
> > > Hey @Harishwarrior Is this Issues comes under Hacktoberfest , so that can I work on this issue ,. can you please assign me on this issue
> > 
> > Yes it does
> 
> Can you please add hacktoberfest label , Thanks Man
> 

Done, check now. Happy hacking.

**Comment by msramesh2k1** [comment]
Hey @Harishwarrior which branch I have to Work

**Comment by Harishwarrior** [comment]
> Hey @Harishwarrior which branch I have to Work 

Master
