### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by Harishwarrior** [CSEKINGS/student_app#8]
Restructure this project to MVC and get hacktoberfest accepted label

**Comment by Shash0501** [comment]
@Harishwarrior Sir, I would take up this issue
But can you please elaborate on what you mean by **Restructure this Project**?

**Comment by Harishwarrior** [comment]
> @Harishwarrior Sir, I would take up this issue
> But can you please elaborate on what you mean by **Restructure this Project**?

The project works, but it's a mess in code structure. Would be great if someone can refactor it to MVC or MVVM.

**Comment by yatendra2001** [comment]
Hi @Harishwarrior , I would like to take up this issue, I have made several projects using MVC. Could you please assign this to me?

**Comment by Harishwarrior** [comment]
> Hi @Harishwarrior , I would like to take up this issue, I have made several projects using MVC. Could you please assign this to me?

Done!. Happy hacking.

**Comment by yatendra2001** [comment]
Hi @Harishwarrior, I have resolved this issue and attached screenshots in PR.
