### ISSUE TITLE
Migrate to Null safety + Upgrade project to Flutter 2.5.2.

### ISSUE THREAD

**Issue by Harishwarrior** [CSEKINGS/student_app#9]
Upgrade the project and get hacktoberfest batch.

**Comment by AyushTripathi28** [comment]
Hello, I am participating in Hacktoberfest this year. I want to contribute to this issue. Kindly assign me this issue.

**Comment by Harishwarrior** [comment]
> Hello, I am participating in Hacktoberfest this year. I want to contribute to this issue. Kindly assign me this issue.

Done!. You can contribute now. Check the readme for credentials.

**Comment by AyushTripathi28** [comment]
thanks for assigning. ok, I will check.

**Comment by Harishwarrior** [comment]
c42cc461f63c96ca9e9a7be80bd4ad116fffcb75

**Comment by Harishwarrior** [comment]
> thanks for assigning. ok, I will check.

Migration is done already. But, the profile is showing unknown (due to null check). If you can fix that, please create a PR. I'll look into it.![Screenshot_20211007-230117.jpg](https://user-images.githubusercontent.com/38380040/136434754-fefdcab8-497d-45db-9e5e-4b6f4fd36008.jpg)
